### ISSUE TITLE
this is a mess

### ISSUE THREAD

**Issue by cybershrapnel** [AspireOrg/aspirewallet#2]
You guys seem to be at a dead end.  I don't see how you will ever package this docker python setup into a usable application...?
What's the plan because this install setup is pretty much unviable. I've got gasp up and running and writing op_returns and files to it, but I'm not even gonna bother with this mess. Not even sure what to say... Who's in charge here? You guys have enabled some really neat features but noone is ever gonna run this on a localhost web port like this. I think you know this though. So what's the plan is my question? How are you taking this to production installation???

**Comment by cybershrapnel** [comment]
and the webwallet??  who thought the keyboard lockout feature was a good idea? I get it, but that is literally a HUGE barrier to entry, I tried it once, i won't try it again... and the quick short password thing didn't work.

**Comment by jimblasko** [comment]
> and the webwallet?? who thought the keyboard lockout feature was a good idea? I get it, but that is literally a HUGE barrier to entry, I tried it once, i won't try it again... and the quick short password thing didn't work.

Hi there, to answer both of these questions for you,

Q1. "who thought the keyboard lockout feature was a good idea? I get it, but that is literally a HUGE barrier to entry, I tried it once, i won't try it again"

A1. The keyboard feature is not locked out. If you already have text in the password box the keyboard feature becomes unnecessary. If you want to use the on screen keyboard simply remove any text that is already in the password box.

Q2. the quick short password thing didn't work.

A2. The quick link and password works fine. It's an available option when you create a fresh new wallet.  You just need to create a short password for yourself, and it will give you the quick link . I've just created an example for anyone to verify that it works fine. They can login with the password "testing" and the quick link provided below it. 
The password is:   testing
The quick link is:   https://aspirewallet.com/#cp=U2FsdGVkX194152yzg/DvT3jrE/cqMrkiq3ektXcyCxT97SUhscUjNSjAz+XXvvkvDXbCLyCXMF0S9UV0RR0u5b8k52oLzyiR5lzBHitQgLBYtwG98YorDhkCfG1IHrx++AmE87YqAYT8tQCQUdv1g==


Whoever decides to check this first, will find a reward of ASP in the wallet and they may take the coins.

**Comment by jimblasko** [comment]
Who ever looks 

> You guys seem to be at a dead end. I don't see how you will ever package this docker python setup into a usable application...? What's the plan because this install setup is pretty much unviable. I've got gasp up and running and writing op_returns and files to it, but I'm not even gonna bother with this mess. Not even sure what to say... Who's in charge here? You guys have enabled some really neat features but noone is ever gonna run this on a localhost web port like this. I think you know this though. So what's the plan is my question? How are you taking this to production installation???

Thanks for checking out Aspire,we appreciate that you found and tried it. For op_return you can simply run the gAsp node and nothing else is necessary. We do have a non docker version of gAsp that you can use.  gAsp is an opensource blockchain and is the gas for Aspire so that's why it was included in the original docker that Matt Smith released. Some changes have been made since then. We are currently in the middle of launching some new federated nodes . That should make install easier. Thanks again for checking out the projects. If you have more questions please shoot them over.

**Comment by cybershrapnel** [comment]
yah, i meant no offense :P  don't need the pr response lol
was genuinely curious about the state of things, guess i wait for that federated code release :P
i only play with things i like, and I only comment about things that i don't like about stuff I like when I care so... I see how what I wrote might be sounding like I was attacking... was not meant that way :P
I was trying to do some dev work and the aspire install just made my head spin lol sorry

FYI, did jon show you we got file uploads working and scanning the chain for files.
![image](https://github.com/AspireOrg/aspirewallet/assets/17352697/4f4ded21-eb7e-4d95-9c9b-7cce72950cfb)

also, implemented a fast syncing option that installs and runs gaspcoin from your github repo using our app, and then fast syncs the chain data up to February of this year so you don't have to sync it for hours.

![image](https://github.com/AspireOrg/aspirewallet/assets/17352697/4e1204ec-3656-4c9c-8c15-7a4f9ef2725b)
